### ISSUE TITLE
Twinkle dropdown bar pushes other items across upon page load

### ISSUE THREAD

**Issue by S-U-M-1** [azatoth/twinkle#385] opened 2017-06-11 19:59 UTC
I'm sure every Wikipedian using Twinkle has encountered this annoyance, but upon every page load, the Twinkle dropdown bar in the top-right of the page pushes the other items across to the left due to it loading later than all of them. This has resulted in me clicking the wrong buttons countless times. If possible, please fix this issue.

**Comment by MusikAnimal** [comment] 2017-06-12 16:48
Duplicate of #336

This unfortunately is not an easy issue to fix, and also is not unique to Twinkle. Any JS gadget that manipulates the DOM after some asynchronous requests will suffer from the same behaviour. The major inconvenience here is the Vector design that puts the dropdown menus after the tabs. Again follow #336 for updates. There are some things we could try, but no promises :-/

**Closed by MusikAnimal** 2017-06-12 16:48 UTC
